.TH DIRINDEX 1 2021-07-05

.SH NAME
dirindex \- directory indexer

.SH SYNOPSIS
dirindex [\fB\-s\fR \fIFORMAT\fR] \fIPATH\fR [\fIPATH\fR...]

.SH DESCRIPTION
\fBdirindex\fR generates an HTML list of all files in a directory.

.SH OPTIONS
.TP
.BI "\-s" " \fIFORMAT\fR"
Change the output format given to the find command's "-printf" action. Default:
"<li><a href=\\"%p\\">%p</a></li>\\n".

.SH EXAMPLE(S)
.EX
dirindex -s '<li><a href=\\"%p\\">%f</a></li>' archive > archiveindex.html
.EE

.SH SEE ALSO
\fBfind\fR(1),
\fBssg-build\fR(1).
