.TH GENINDEX 1 2021-07-05

.SH NAME
genindex \- generate index

.SH SYNOPSIS
genindex [\fB\-t\fR \fITEMPLATE\fR] \fIFILE\fR

.SH DESCRIPTION
\fBgenindex\fR generates an HTML index file from a Recutils database.

.SH OPTIONS
.TP
.BI "\-t" " \fITEMPLATE\fR"
Change the template given to "recfmt". Default:
.EX
<li>
<b>{{Date}}:</b>
<a href="{{File}}">{{Name}}</a>
{{Extra}}
</li>
.EE

.SH EXAMPLE(S)
.EX
genindex -t '
<li>
{{Date}}:
<a href="{{File}}">{{Name}}</a>
</details>
<summary>Extra<summary>
{{Extra}}
<details>
</li>
\' index.rec > index.html
.EE

.SH SEE ALSO
\fBrecfmt\fR(1)

\fBdirindex\fR(1),
\fBgenrss\fR(1),
\fBgentoc\fR(1),
\fBmarkdown2html\fR(1),
\fBssg-build\fR(1),
\fBwraphtml\fR(1).
