.TH GENTOC 1 2021-07-05

.SH NAME
gentoc \- generate table of contents

.SH SYNOPSIS
gentoc \fIFILE\fR

.SH DESCRIPTION
\fBgentoc\fR generates a table of contents for a given HTML file. The outermost
<ol> tag will have the 'toc' class so it can be customized with CSS. Note that
gentoc only prints the table of contents \fBwithout\fR the actual HTML file.

.SH EXAMPLE(S)
.EX
gentoc file1.html > file2.html
.EE
.EX
{ gentoc file1.html; cat file1.html ;} > file2.html
.EE

.SH SEE ALSO
\fBssg-build\fR(1).
