#!/bin/sh

export output="$(mktemp -dp /tmp 'ssg-XXXXX')"
# PATH="$PATH:unnamed-ssg"
indexsep="|"

# # Uncomment if $output is not a temporary directory
# [ -d "$output" ] && rm -r "$output"
# mkdir -p "$output"

# Mics
find -L * -exec mvfiles '{}' +

# RSS
rss -F"$indexsep" index.db | wraphtml -t template.xml > "$output/rss.xml"

# Index
index -F"$indexsep" index.db | wraphtml > "$output/index.html"

echo "Generated Website outputted to $output"
