#!/bin/sh

outfile="index.html"

while getopts sf arg; do
	case $arg in
		s) sortfile=1 ;;
		f) force=1 ;;
	esac
done
shift $(expr $OPTIND - 1)


[ ! "$force" ] && [ -f "$outfile" ] && { echo "'$outfile' already exists."; exit 1 ;}
[ $# = 0 ] && { echo "No paths given."; exit 1 ;}

for path do
	find "$path" ! -path "$path/$outfile" -type f \
		-printf '<li><a href="%P">%P</a></li>\n' > "$outfile"

	[ "$sortfile" ] && sort -o "$outfile" "$outfile"
done
