#!/usr/bin/awk -f

BEGIN { print "<ul>" }

/^#/ { next }
/^$/ { next }

{
	print "<li>"
	printf "<b>%s:</b>\n", $1
	printf "<a href=\"%s\">%s</a>\n", $3, $2
	if ($4) {
		if (length($4) > 50)
			printf "<details><summary>Extra</summary>%s</details>\n", $4
		else
			printf "(%s)\n", $4
	}
	print "</li>"
}

END { print "</ul>" }
