#!/usr/bin/env python

import json
import argparse

parser = argparse.ArgumentParser(description='Generate an index HTML from a JSON database.')
parser.add_argument('json_file', help='input JSON file', metavar='FILE', nargs='?', default='/dev/stdin')
args = parser.parse_args()

with open(args.json_file, encoding='utf-8') as f:
    json_data = json.load(f)

print("<ul>")
for entry in json_data:
    print("<li>")
    print(f"<b>{entry['title']}:</b>")
    print(f"<a href='{entry['file']}'>{entry['title']}</a>")
    if 'tags' in entry:
        print(f"{entry['tags']}")
    if 'comment' in entry:
        print(f"<details><summary>Extra</summary>{entry['comment']}</details>")
    print("</li>")
print("</ul>")
