#!/usr/bin/env python

import json
import hashlib
import argparse
import mimetypes

parser = argparse.ArgumentParser(description='Generate an RSS feed from a JSON database.')
parser.add_argument('json_file',           help='input JSON file',
        default='/dev/stdin', nargs='?', metavar='FILE')
parser.add_argument('-t', '--title',       help='RSS feed title',       required=True)
parser.add_argument('-l', '--link',        help='RSS feed link',        required=True)
parser.add_argument('-d', '--description', help='RSS feed description', required=True)
args = parser.parse_args()

with open(args.json_file, encoding='utf-8') as f:
    json_data = json.load(f)

print('<?xml version="1.0" encoding="UTF-8"?>')
print('<rss version="2.0">')
print('<channel>')
print(f'<title>{args.title}</title>')
print(f'<link>{args.link}</link>')
print(f'<description>{args.description}</description>')

for entry in json_data:
    print("<item>")
    print(f"<title>{entry['title']}</title>")
    print(f"<link>{entry['file']}</link>")
    with open(entry['file'], 'rb') as f:
        entry['md5'] = hashlib.md5(f.read()).hexdigest() # Get md5 hash for guid
        print(f"<guid>{entry['md5']}</guid>")
    print(f"<pubDate>{entry['date']}</pubDate>")
    print('<description>')
    if 'comment' in entry:
        print(entry['comment'])
    if mimetypes.guess_type(entry['file'])[0] == "text/html": # Include in feed if HTML file
        print('<![CDATA[')
        with open(entry['file'], encoding='utf-8') as f:
            print(f.read())
        print(']]>')
    print('</description>')
    print("</item>")

print('</channel>')
print('</rss>')
