#!/usr/bin/awk -f

# Generate an RSS feed from an index database. Do not forget to set the field
# separator using the -F flag. See README for more information.
# genrss -F'|' index.db > rss.xml

/^[#+$]|^$/ {next}

{
	title=$3
	date=$1
	file=$2
	print "<item>"
	printf "<title>%s</title>\n", title
	printf "<link>%s</link>\n", file
	printf "<guid>%s</guid>\n", file
	printf "<pubDate>%s</pubDate>\n", date
	print "<description><![CDATA["

	if (ext[split(file,ext,".")] == "html" && system("test -f " file)==0)
		while (getline tmp<file) {print tmp}
	else
		printf "<a href=\"%s\">%s</a>\n", file, file

	print $4
	print "]]></description>"
	print "</item>"
}
