#!/bin/sh

# Generate a table of contents form a HTML file. Then append the original file.
# gentoc file1.html > file2.html

temp=$(mktemp)
cat "${1:--}" > "$temp"

tr '\n' ' ' < "$temp" | tr -d '\t' |
	grep -o '<h[0-6][^>]*>[^<]\+</h[0-6]>' |
	awk -F'</?h[1-6][^>]*>' '
	BEGIN {
		print "<ol class=\"toc\">"
	}

	{
		current_level = substr($0, 3, 1) # Get heading size (<hX>)
		if (! last_level) last_level = current_level
		diff_level = current_level - last_level

		if (diff_level != 0) {
			for (i = 0; i < diff_level; i++) print "<ol>"
			for (i = 0; i > diff_level; i--) print "</ol>"
		}
		printf "<li>%s</li>\n", $2
		last_level = current_level
	}

	END {
		print "</ol>"
	}

'
cat "$temp"
rm "$temp"
