#!/usr/bin/env python

import sys
from bs4 import BeautifulSoup

for file in sys.argv[1:]:
    with open(file, encoding='utf-8') as f:
        file_contents = f.read()
        soup = BeautifulSoup(file_contents, 'html.parser')
        print('<ol class="toc">')

        header_level_old = 1
        for header in soup.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6']):
            header_level_current = int(header.name[1])
            diff_level = header_level_current - header_level_old
            while diff_level > 0:
                print("<ol>")
                diff_level -= 1
            while diff_level < 0:
                diff_level += 1
                print("</ol>")
            print(f"<li>{header.text}</li>")
            header_level_old = header_level_current
        while 1 < header_level_current:
            print("</ol>")
            header_level_current -= 1

        print('</ol>')
        print(file_contents)
