#!/usr/bin/awk -f

BEGIN {
	print "<ul>"
}

/^#/ { next }

/^\+/ {
	print "</ul>"
	printf "<h3>%s</h3>\n", substr($0, 2)
	print "<ul>"
	next
}

{
	print "<li>"
	printf "<b>%s:</b>\n", $1
	printf "<a href=\"%s\">%s</a>\n", $2, $3
	if ($4)
		printf "(<a href=\"%s\">Källa</a>)\n", $4
	print "</li>"
}

END {
	print "</ul>"
}
