#!/bin/sh

# Run specific commands depending on the input files extension. See README for
# more information.
# mvfiles file1 file2

for infile do
	outfile="$output/$infile"
	outdir=${outfile%/*}
	basename=${outfile%.*} # Outfile without extention
	nameonly=${basename##*/} # Without extention or directory path

	echo "$infile"
	[ -d "$infile" ] && mkdir -p "$outfile" && continue

	case $infile in
		template.*|scripts/*|archive/*)
			cp "$infile" "$outfile"
			;;
		#*.jpg|*.png)
		#	convert "$infile" -strip "$outfile"
		#	;;
		*.html)
			{ gentoc "$infile"; cat "$infile" ;} | wraphtml > "$outfile"
			;;
		#*.md)
		#	pandoc -f gfm -f html "$infile" | gentoc | wraphtml > "$basename.html"
		#	;;
		#*.tex)
		#	pdflatex -output-directory "$outdir" "$infile" > /dev/null 2>&1
		#	cp "$infile" "$outfile"
		#	;;
		*)
			cp "$infile" "$outfile"
			;;
	esac
done
