#!/bin/sh

help() {
cat <<EOF
usage: relpath [-h] DIR1 [DIR2 ...]

Find relative paths in HTML files.

options:
   -h print help message
EOF
}

while getopts h flag; do
	case $flag in
		h) help; exit;;
		\?) help; exit 1;;
	esac
done
shift "$((OPTIND - 1))"

for dir do
	find "$dir" -type f -name '*.html' \
		-exec grep -HP "(src|href)=[\"'][^/](?!\w+://)" '{}' +
done
