#!/bin/sh

help() {
cat <<EOF
usage: wraphtml [-h] [-R REGEX] [-t TEMPLATE] FILE

Convert Markdown files to HTML files.

options:
   -h print    help message
   -R REGEX    Specify marker where the file is going to be
               injected (default $regex_old)
   -t TEMPLATE Specify template HTML file
               (default $template_old)
EOF
}

regex_old="^\s*<!--WRAPHTML-->$"
template_old="template.html"

while getopts t:R: arg; do
	case $arg in
		t) template=$OPTARG;;
		R) regex=$OPTARG;;
		h) help; exit;;
		\?) help; exit 1;;
	esac
done
shift $(expr $OPTIND - 1)

sed "/${regex:=$regex_old}/r ${1:-/dev/stdin}" \
	"${template:=$template_old}"
