#!/bin/sh

# Inject the file when the string '<!--WRAPHTML-->' is found in the template.
# wraphtml file.html > out.html
# ... | wraphtml [ -t template_file ] > out.html

while getopts t: arg; do
	case $arg in
		t) template=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1)

sed "/^\s*<!--WRAPHTML-->$/r ${1:-/dev/stdin}" "${template:-template.html}"
